import reactLogo from './images/reactLogo.png';
import omnifoodHero from './images/Omnifood/Omnifood-Hero.PNG';
import omnifoodAbout from './images/Omnifood/Omnifood-About.PNG';
import omnifoodContact from './images/Omnifood/Omnifood-Contact.PNG';
import omnifoodHow from './images/Omnifood/Omnifood-HowItWorks.PNG';
import omnifoodImgGallery from './images/Omnifood/Omnifood-ImageGallery.PNG';
import omnifoodLocations from './images/Omnifood/Omnifood-Locations.PNG';
import omnifoodPricing from './images/Omnifood/Omnifood-Pricing.PNG';
import omnifoodTestimonials from './images/Omnifood/Omnifood-Testimonials.PNG';

const cases = [
    {
        "ProjectID": 1,
        "path": "HB-ordering-site",
        "title": "Increase scalability with an e-commerce site",
        "image": reactLogo,
        "image-alt": "main img alt text",
        "who": "Heavenly Buds",
        "what": "UI | UX | WordPress website design | Custom Theme",
        "result": "Over 140% increase in sales revenue",
        "appName": "Heavenly Buds Ordering Website",
        "link": "http://orders.heavenlybuds.com/",
        "github": "",
        "done-img1": reactLogo,
        "done-img1-alt": "alt text",
        "done-img2": reactLogo,
        "done-img2-alt": "alt text",
        "done-img3": reactLogo,
        "done-img3-alt": "alt text",
        "done-img4": reactLogo,
        "done-img4-alt": "alt text",
        "summary": `Heavenly Buds is a licensed recreational cannabis producer and processor in WA state.  They serve over 70 retail locations across the state with multiple brands and products.   They were previously receiving orders through email but were running into inventory and order fulfillment issues.  The goal was to create an online application to make their ordering process easier for their customers, reduce order fulfillment issues while increasing efficiency in their processes.
        The result of implementing the e-commerce site gave Heavenly Buds the ability to double their retail customer count and produce an increase of over 140% in overall sales revenue.  The ordering website currently processes over $1.2M in sales annually.`,
        "technology": "HTML | CSS | JavaScript | jQuery | WordPress",
        "role": "I contributed to the project by developing the UI/UX, custom theme and e-commerce website architecture design.  Coding was done by freelancer, Mario Espinosa.",
        "process": `I started by interviewing Heavenly Buds management to find out exactly what issues they were looking to resolve.  Email orders were taking a long time to process and they often ran out of inventory of certain products while customers were still ordering them.  This caused additional time going back and forth with retailers.  They also wanted an application that was easy to use and displayed the essence of their brands.
        I then connected with some of Heavenly Buds’ retail customers to find out what was important to this group.  The retailers are overwhelmed with phone calls, new companies seeking shelf space and customer issues.  They wanted something fast and easy to use, something that would make communication between the company seamless and something that had visuals of the products and important product info to make their purchase decisions.
        After defining each group’s needs, I sketched out the site theme, design and data flow.  Then, collaboration with Mario Espinosa began to code out the project.  We decided to use WordPress which addressed many of each group’s needs – ease of use for ordering and updating inventory, making product out of inventory unavailable and instant order status communication.`,
        "process-img1": reactLogo,
        "process-img1-alt": "alt text",
        "process-img2": reactLogo,
        "process-img2-alt": "alt text",
        "process-img3": reactLogo,
        "process-img3-alt": "alt text",
        "process-img4": reactLogo,
        "process-img4-alt": "alt text"
    },
    {
        "ProjectID": 2,
        "path": "Land4Wholesale-website",
        "title": "Create Property Showcase to increase sales",
        "image": reactLogo,
        "image-alt": "alt text",
        "who": "CM3 Real Estate",
        "what": "UI | UX | Front End coding | Video editing",
        "result": "Cut days on market in half",
        "appName": "Land4Wholesale.com",
        "link": "",
        "github": "",
        "done-img1": reactLogo,
        "done-img1-alt": "alt text",
        "done-img2": reactLogo,
        "done-img2-alt": "alt text",
        "done-img3": reactLogo,
        "done-img3-alt": "alt text",
        "done-img4": reactLogo,
        "done-img4-alt": "alt text",
        "summary": `Land4Wholesale.com was owned by real estate investing company, CM3 Real Estate.  The company mainly focuses on commercial rentals but occasionally purchases raw land with optional zoning for commercial use.  Over time they created a stockpile of properties that they wanted to liquidate.  The goal was to create a website to showcase the properties to a wide range of both residential and commercial property buyers, deliver critical unique information needed to purchase raw land and market the properties on multiple platforms.`,
        "technology": "HTML | CSS | JavaScript | WordPress",
        "role": "I was sole contributor on each project – UI/UX, property data research, website design, video editing, Front-End coding and 3rd party integrations utilizing Zapier.com",
        "process": `I began the process by interviewing real estate agents and brokers on what kind of raw land properties they sought to purchase, what are the key property details needed to make a purchase and how do they determine a property’s value.  With this information I began to design an e-commerce style website which showcased each property and highlighted their needs.  Information and graphics from zoning to property GPS coordinates and boundary lines to 100-year flood zones and everything in between was included for each property.  
        Very quickly after launch we discovered there was a low response rate due to lack of compelling images, people had a hard time envisioning the possibilities with just plain pictures of trees and dirt.  We decided to have drones survey the properties and surrounding areas and marketed those videos for each property.  This dramatically increased the amount of interest in the properties and allowed for a 50% decrease in days on market which led to a much quicker liquidation of the properties.`,
        "process-img1": reactLogo,
        "process-img1-alt": "alt text",
        "process-img2": reactLogo,
        "process-img2-alt": "alt text",
        "process-img3": reactLogo,
        "process-img3-alt": "alt text",
        "process-img4": reactLogo,
        "process-img4-alt": "alt text"
    },
    {
        "ProjectID": 3,
        "path": "stocks-analysis",
        "title": "Company stock news & info with investing education",
        "image": reactLogo,
        "image-alt": "alt text",
        "who": "Useful for New Investors",
        "what": "UI | UX | Design | Front End coding | RESTful APIs",
        "result": "Increased understanding of stock & options investing",
        "appName": "Stocks Analysis",
        "link": "https://miguelr215.github.io/stocks-analysis/",
        "github": "https://github.com/miguelr215/stocks-analysis",
        "done-img1": reactLogo,
        "done-img1-alt": "alt text",
        "done-img2": reactLogo,
        "done-img2-alt": "alt text",
        "done-img3": reactLogo,
        "done-img3-alt": "alt text",
        "done-img4": reactLogo,
        "done-img4-alt": "alt text",
        "summary": `This project was a course assignment by Thinkful.  The goal was to create an application which uses at least 1 RESTful API to pull and display data dependent upon the user’s criteria request.  I created an application which pulls public companies’ data, news and stock information.  In addition, an Education section was added to pull YouTube videos teaching about investing in stocks and options.`,
        "technology": "HTML | CSS | JavaScript | jQuery | RESTful APIs",
        "role": "I was sole contributor on the entire project – UI/UX, design, Front-End and API coding",
        "process": `I started this process by considering what kind of application I wanted to build.  After deciding on stocks as my topic I researched numerous APIs and decided to use the free stock API through RapidAPI.  The original sketch idea was simple, a text field for the user to enter the company they wanted to research and a way to display the returned information.  Company stock info and news were separated into their own sections.  After review by my mentor, it was suggested to add an Education section for users that were unfamiliar with many of the terms and stock information that was displayed so I utilized the YouTube API to pull videos teaching about investing in stocks and options.  This was a great project which taught me a lot about APIs, AJAX and error handling.`,
        "process-img1": reactLogo,
        "process-img1-alt": "alt text",
        "process-img2": reactLogo,
        "process-img2-alt": "alt text",
        "process-img3": reactLogo,
        "process-img3-alt": "alt text",
        "process-img4": reactLogo,
        "process-img4-alt": "alt text"
    },
    {
        "ProjectID": 4,
        "path": "omnifood",
        "title": "Food Delivery Service Website Developmenet",
        "image": omnifoodHero,
        "image-alt": "Omnifood Food Delivery website",
        "who": "Omnifood Food Delivery",
        "link": "https://miguelr215.github.io/Omnifood/",
        "github": "https://github.com/miguelr215/Omnifood",
        "what": "Front End coding",
        "result": "Responsive single page application",
        "appName": "Omnifood Food Delivery",
        "done-img1": omnifoodHero,
        "done-img1-alt": "Omnifood Food Delivery Hero",
        "done-img2": omnifoodAbout,
        "done-img2-alt": "Omnifood Food Delivery About section",
        "done-img3": omnifoodTestimonials,
        "done-img3-alt": "Omnifood Testimonials section",
        "done-img4": omnifoodContact,
        "done-img4-alt": "Omnifood Contact Us section",
        "summary": `This was a course assignment on Udemy focusing on JavaScript.  The goal was to create a website for a fictitious food delivery company utilizing JavaScript and jQuery.  The result was a single page application which utilizes different JavaScript and CSS techniques.`,
        "technology": "HTML | CSS | JavaScript | jQuery",
        "role": "I completed all Front-End coding",
        "process": `The images were all supplied by the Udemy course.  The goal was to create a website for a fictitious food delivery company utilizing JavaScript and jQuery.  The website was designed to display critical information that a customer would want to know – description of the company and benefits of their services, food examples, pricing, testimonials, contact.  Each section of the website incorporated different CSS, JavaScript and/or jQuery animations, methods or techniques.  This was a great course which taught me foundational and advanced JavaScript and CSS coding.`,
        "process-img1": omnifoodImgGallery,
        "process-img1-alt": "Omnifood food image gallery highlight effect",
        "process-img2": omnifoodHow,
        "process-img2-alt": "Omnifood image animation effect",
        "process-img3": omnifoodPricing,
        "process-img3-alt": "Omnifood pulse animation on pricing",
        "process-img4": omnifoodLocations,
        "process-img4-alt": "Omnifood use & manipulation of icons"
    }
];

export default cases;