import reactLogo from './images/reactLogo.png';

const cases = [
    {
        "ProjectID": 1,
        "path": "",
        "title": "Increase scalability with an e-commerce site",
        "image": reactLogo,
        "image-alt": "main img alt text",
        "who": "Heavenly Buds",
        "what": "UI | UX | Wordpress website design | Custom Theme",
        "result": "Over 140% increase in sales",
        "app-name": "Heavenly Buds Ordering Website",
        "done-img1": "",
        "done-img1-alt": "",
        "done-img2": "",
        "done-img2-alt": "",
        "summary": "",
        "technology": "HTML | CSS | JavaScript | jQuery | WordPress",
        "problem": "",
        "role": "",
        "process": "",
        "process-img1": "",
        "process-img1-alt": "",
        "process-img2": "",
        "process-img2-alt": "",
    },
    {
        "ProjectID": 2,
        "path": "",
        "title": "Accumulate company stock info & investing education",
        "image": reactLogo,
        "image-alt": "",
        "who": "New Investors",
        "what": "UI | UX | Design | Develop",
        "result": "Increased understanding of stock & options investing",
        "app-name": "Stock Analysis",
        "done-img1": "",
        "done-img1-alt": "",
        "done-img2": "",
        "done-img2-alt": "",
        "summary": "",
        "technology": "HTML | CSS | JavaScript | jQuery",
        "problem": "",
        "role": "",
        "process": "",
        "process-img1": "",
        "process-img1-alt": "",
        "process-img2": "",
        "process-img2-alt": "",
    },
    {
        "ProjectID": 3,
        "path": "",
        "title": "",
        "image": reactLogo,
        "image-alt": "",
        "who": "CM3 Real Estate",
        "what": "",
        "result": "",
        "app-name": "Land4Wholesale.com",
        "done-img1": "",
        "done-img1-alt": "",
        "done-img2": "",
        "done-img2-alt": "",
        "summary": "",
        "technology": "",
        "problem": "",
        "role": "",
        "process": "",
        "process-img1": "",
        "process-img1-alt": "",
        "process-img2": "",
        "process-img2-alt": "",
    },
    {
        "ProjectID": 4,
        "path": "omnifood",
        "title": "",
        "image": reactLogo,
        "image-alt": "",
        "who": "Omnifood",
        "what": "",
        "result": "",
        "app-name": "",
        "done-img1": "",
        "done-img1-alt": "",
        "done-img2": "",
        "done-img2-alt": "",
        "summary": "",
        "technology": "",
        "problem": "",
        "role": "",
        "process": "",
        "process-img1": "",
        "process-img1-alt": "",
        "process-img2": "",
        "process-img2-alt": "",
    }
];

export default cases;